@@image_mime_types ||= { ".gif" => "image/gif",
                         ".ief" => "image/ief",
                         ".jpe" => "image/jpeg",
                         ".jpeg" => "image/jpeg",
                         ".jpg" => "image/jpeg",
                         ".pbm" => "image/x-portable-bitmap",
                         ".pgm" => "image/x-portable-graymap",
                         ".png" => "image/png",
                         ".pnm" => "image/x-portable-anymap",
                         ".ppm" => "image/x-portable-pixmap",
                         ".ras" => "image/cmu-raster",
                         ".rgb" => "image/x-rgb",
                         ".tif" => "image/tiff",
                         ".tiff" => "image/tiff",
                         ".xbm" => "image/x-xbitmap",
                         ".xpm" => "image/x-xpixmap",
                         ".xwd" => "image/x-xwindowdump" }.freeze 