# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 29) do

  create_table "articles", :force => true do |t|
    t.column "user_id",     :integer
    t.column "category_id", :integer
    t.column "title",       :string
    t.column "body",        :text
    t.column "created_at",  :datetime
    t.column "updated_at",  :datetime
    t.column "description", :text
  end

  create_table "avatars", :force => true do |t|
    t.column "user_id",      :integer
    t.column "parent_id",    :integer
    t.column "content_type", :string
    t.column "filename",     :string
    t.column "thumbnail",    :string
    t.column "size",         :integer
    t.column "width",        :integer
    t.column "height",       :integer
  end

  create_table "bios", :force => true do |t|
    t.column "user_id",      :integer
    t.column "about",        :text
    t.column "interests",    :text
    t.column "music",        :text
    t.column "films",        :text
    t.column "television",   :text
    t.column "books",        :text
    t.column "heroes",       :text
    t.column "author_about", :text
  end

  create_table "blogs", :force => true do |t|
    t.column "user_id", :integer
  end

  create_table "categories", :force => true do |t|
    t.column "name",        :string
    t.column "description", :text
  end

  create_table "comments", :force => true do |t|
    t.column "user_id",          :integer
    t.column "post_id",          :integer
    t.column "body",             :text
    t.column "created_at",       :datetime
    t.column "commentable_id",   :integer
    t.column "commentable_type", :string
  end

  create_table "emails", :force => true do |t|
    t.column "from",              :string
    t.column "to",                :string
    t.column "last_send_attempt", :integer,  :default => 0
    t.column "mail",              :text
    t.column "created_on",        :datetime
  end

  create_table "friendships", :force => true do |t|
    t.column "user_id",     :integer
    t.column "friend_id",   :integer
    t.column "status",      :string
    t.column "created_at",  :datetime
    t.column "accepted_at", :datetime
  end

  create_table "im_contacts", :force => true do |t|
    t.column "profile_id", :integer
    t.column "contact",    :string
    t.column "service",    :string
  end

  create_table "messages", :force => true do |t|
    t.column "sender_id",        :integer,                  :null => false
    t.column "receiver_id",      :integer,                  :null => false
    t.column "subject",          :string,   :default => "", :null => false
    t.column "body",             :text
    t.column "created_at",       :datetime
    t.column "read_at",          :datetime
    t.column "sender_deleted",   :boolean
    t.column "receiver_deleted", :boolean
    t.column "sender_purged",    :boolean
    t.column "receiver_purged",  :boolean
  end

  add_index "messages", ["sender_id"], :name => "index_messages_on_sender_id"
  add_index "messages", ["receiver_id"], :name => "index_messages_on_receiver_id"

  create_table "news", :force => true do |t|
    t.column "user_id",    :integer
    t.column "title",      :string
    t.column "body",       :text
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
  end

  create_table "posts", :force => true do |t|
    t.column "blog_id",    :integer
    t.column "title",      :string
    t.column "body",       :text
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
  end

  create_table "profiles", :force => true do |t|
    t.column "user_id",    :integer, :default => 0,  :null => false
    t.column "first_name", :string
    t.column "last_name",  :string
    t.column "gender",     :string
    t.column "birthdate",  :date
    t.column "city",       :string
    t.column "county",     :string
    t.column "post_code",  :string
    t.column "lat",        :float
    t.column "lng",        :float
    t.column "occupation", :string,  :default => ""
    t.column "website",    :string
  end

  create_table "sessions", :force => true do |t|
    t.column "session_id", :string
    t.column "data",       :text
    t.column "updated_at", :datetime
  end

  add_index "sessions", ["session_id"], :name => "index_sessions_on_session_id"
  add_index "sessions", ["updated_at"], :name => "index_sessions_on_updated_at"

  create_table "taggings", :force => true do |t|
    t.column "tag_id",        :integer
    t.column "taggable_id",   :integer
    t.column "taggable_type", :string
    t.column "created_at",    :datetime
  end

  add_index "taggings", ["tag_id"], :name => "index_taggings_on_tag_id"
  add_index "taggings", ["taggable_id", "taggable_type"], :name => "index_taggings_on_taggable_id_and_taggable_type"

  create_table "tags", :force => true do |t|
    t.column "name", :string
  end

  create_table "users", :force => true do |t|
    t.column "login",                     :string
    t.column "email",                     :string
    t.column "crypted_password",          :string,   :limit => 40
    t.column "salt",                      :string,   :limit => 40
    t.column "created_at",                :datetime
    t.column "updated_at",                :datetime
    t.column "remember_token",            :string
    t.column "remember_token_expires_at", :datetime
    t.column "activation_code",           :string,   :limit => 40
    t.column "activated_at",              :datetime
    t.column "new_email",                 :string
    t.column "email_activation_code",     :string,   :limit => 40
    t.column "password_reset_code",       :string,   :limit => 40
    t.column "admin",                     :boolean,                :default => false
    t.column "permalink",                 :string
    t.column "hits",                      :integer,                :default => 0
  end

  create_table "walls", :force => true do |t|
    t.column "user_id", :integer
  end

end
