# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 9) do

  create_table "avatars", :force => true do |t|
    t.column "user_id",      :integer
    t.column "parent_id",    :integer
    t.column "content_type", :string
    t.column "filename",     :string
    t.column "thumbnail",    :string
    t.column "size",         :integer
    t.column "width",        :integer
    t.column "height",       :integer
  end

  create_table "bios", :force => true do |t|
    t.column "user_id",    :integer
    t.column "about",      :text
    t.column "interests",  :text
    t.column "music",      :text
    t.column "films",      :text
    t.column "television", :text
    t.column "books",      :text
    t.column "heroes",     :text
  end

  create_table "blogs", :force => true do |t|
    t.column "user_id", :integer
  end

  create_table "posts", :force => true do |t|
    t.column "blog_id",    :integer
    t.column "title",      :string
    t.column "body",       :text
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
  end

  create_table "profiles", :force => true do |t|
    t.column "user_id",    :integer, :default => 0,  :null => false
    t.column "first_name", :string,  :default => ""
    t.column "last_name",  :string,  :default => ""
    t.column "gender",     :string
    t.column "birthdate",  :date
    t.column "city",       :string,  :default => ""
    t.column "county",     :string,  :default => ""
    t.column "post_code",  :string,  :default => ""
    t.column "lat",        :float
    t.column "lng",        :float
    t.column "occupation", :string,  :default => ""
  end

  create_table "users", :force => true do |t|
    t.column "login",                     :string
    t.column "email",                     :string
    t.column "crypted_password",          :string,   :limit => 40
    t.column "salt",                      :string,   :limit => 40
    t.column "created_at",                :datetime
    t.column "updated_at",                :datetime
    t.column "remember_token",            :string
    t.column "remember_token_expires_at", :datetime
    t.column "activation_code",           :string,   :limit => 40
    t.column "activated_at",              :datetime
    t.column "new_email",                 :string
    t.column "email_activation_code",     :string,   :limit => 40
    t.column "password_reset_code",       :string,   :limit => 40
  end

end
